/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.meske.moviemanager;

import hr.meske.dal.ITheGuyRepository;
import hr.meske.dal.RepoFactory;
import hr.meske.utilities.MessageUtils;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 505wL
 */
public class LoginForm extends javax.swing.JFrame {

    private final ITheGuyRepository guyRepo;

    public LoginForm() {
        initComponents();

        guyRepo = RepoFactory.getTheGuyRepository();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tfUsername1 = new javax.swing.JTextField();
        tfPassword1 = new javax.swing.JTextField();
        lbUsername1 = new javax.swing.JLabel();
        lbPassword1 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpLogin = new javax.swing.JPanel();
        tfUsername = new javax.swing.JTextField();
        lbUsername = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jpfPassword = new javax.swing.JPasswordField();
        jpRregister = new javax.swing.JPanel();
        jpRegister = new javax.swing.JPanel();
        tfRegUsername = new javax.swing.JTextField();
        lbUsername2 = new javax.swing.JLabel();
        lbPassword2 = new javax.swing.JLabel();
        btnRegisterLogin = new javax.swing.JButton();
        jpfPassReg = new javax.swing.JPasswordField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(tfUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 33, 157, -1));
        jPanel3.add(tfPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 157, -1));

        lbUsername1.setText("Username");
        jPanel3.add(lbUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 36, -1, -1));

        lbPassword1.setText("Password");
        jPanel3.add(lbPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 75, 85, -1));

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 143, 101, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 230));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpLogin.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 63, 157, -1));

        lbUsername.setText("Username");
        jpLogin.add(lbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 150, -1));

        lbPassword.setText("Password");
        jpLogin.add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 160, -1));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jpLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 101, 40));

        jpfPassword.setText("jPasswordField1");
        jpLogin.add(jpfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 160, -1));

        jTabbedPane1.addTab("Login", jpLogin);

        jpRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpRegister.add(tfRegUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 63, 157, -1));

        lbUsername2.setText("Username");
        jpRegister.add(lbUsername2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 150, -1));

        lbPassword2.setText("Password");
        jpRegister.add(lbPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 160, -1));

        btnRegisterLogin.setText("Register");
        btnRegisterLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterLoginActionPerformed(evt);
            }
        });
        jpRegister.add(btnRegisterLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 101, 40));

        jpfPassReg.setText("jPasswordField1");
        jpRegister.add(jpfPassReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 160, -1));

        javax.swing.GroupLayout jpRregisterLayout = new javax.swing.GroupLayout(jpRregister);
        jpRregister.setLayout(jpRregisterLayout);
        jpRregisterLayout.setHorizontalGroup(
            jpRregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
            .addGroup(jpRregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpRregisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jpRregisterLayout.setVerticalGroup(
            jpRregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
            .addGroup(jpRregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpRregisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Register", jpRregister);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        String guyUsername = tfUsername.getText();
        String guyPassword = jpfPassword.getText();

        if (!guyRepo.SearchTheGuyByUsername(guyUsername)) {
            MessageUtils.showErrorMessage("NotFoundError", "Seems like this Guy doesen't exist!");
            return;
        }

        if (!guyRepo.isPasswordMatch(guyUsername, guyPassword)) {
            MessageUtils.showErrorMessage("AuthorizationError", "Theese credentials don't match up!");
            return;
        }

        if (!guyRepo.isAdmin(guyUsername, guyPassword)) {
            new AdministratorForm().show();
            this.dispose();

        } else {
            try {
                new UserForm().show();
            } catch (Exception ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnRegisterLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterLoginActionPerformed
        String guyUsername = tfRegUsername.getText();
        String guyPassword = jpfPassReg.getText();

        if (guyRepo.SearchTheGuyByUsername(guyUsername)) {
            MessageUtils.showErrorMessage("RegistrationError", "This username is already taken!");
            return;
        }

         guyRepo.createTheGuy(guyUsername, guyPassword);
         
         MessageUtils.showInformationMessage("RegistrationSuccess", "New Guy Created!");
          
    }//GEN-LAST:event_btnRegisterLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginForm().setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegisterLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpLogin;
    private javax.swing.JPanel jpRegister;
    private javax.swing.JPanel jpRregister;
    private javax.swing.JPasswordField jpfPassReg;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbPassword1;
    private javax.swing.JLabel lbPassword2;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JLabel lbUsername1;
    private javax.swing.JLabel lbUsername2;
    private javax.swing.JTextField tfPassword1;
    private javax.swing.JTextField tfRegUsername;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JTextField tfUsername1;
    // End of variables declaration//GEN-END:variables

}
